TICKERS_CONHECIDOS = {
    "PETR4":  {"cd_cvm": 9512,  "nome": "PETROBRAS",              "yf": "PETR4.SA"},
    "PETR3":  {"cd_cvm": 9512,  "nome": "PETROBRAS ON",           "yf": "PETR3.SA"},
    "VALE3":  {"cd_cvm": 4170,  "nome": "VALE",                   "yf": "VALE3.SA"},
    "ITUB4":  {"cd_cvm": 19348, "nome": "ITAU UNIBANCO",          "yf": "ITUB4.SA"},
    "BBDC4":  {"cd_cvm": 906,   "nome": "BRADESCO",               "yf": "BBDC4.SA"},
    "ABEV3":  {"cd_cvm": 23264, "nome": "AMBEV",                  "yf": "ABEV3.SA"},
    "WEGE3":  {"cd_cvm": 5410,  "nome": "WEG",                    "yf": "WEGE3.SA"},
    "BBAS3":  {"cd_cvm": 1023,  "nome": "BANCO DO BRASIL",        "yf": "BBAS3.SA"},
    "ELET3":  {"cd_cvm": 2437,  "nome": "ELETROBRAS",             "yf": "ELET3.SA"},
    "B3SA3":  {"cd_cvm": 21610, "nome": "B3",                     "yf": "B3SA3.SA"},
    "RENT3":  {"cd_cvm": 19739, "nome": "LOCALIZA",               "yf": "RENT3.SA"},
    "EMBR3":  {"cd_cvm": 20087, "nome": "EMBRAER",                "yf": "EMBR3.SA"},
    "KLBN11": {"cd_cvm": 12653, "nome": "KLABIN",                 "yf": "KLBN11.SA"},
    "LREN3":  {"cd_cvm": 8133,  "nome": "LOJAS RENNER",           "yf": "LREN3.SA"},
    "GGBR4":  {"cd_cvm": 3980,  "nome": "GERDAU",                 "yf": "GGBR4.SA"},
    "EQTL3":  {"cd_cvm": 20010, "nome": "EQUATORIAL",             "yf": "EQTL3.SA"},
    "VIVT3":  {"cd_cvm": 17671, "nome": "TELEFONICA BRASIL",      "yf": "VIVT3.SA"},
    "CMIG4":  {"cd_cvm": 2453,  "nome": "CEMIG",                  "yf": "CMIG4.SA"},
    "SANB11": {"cd_cvm": 20532, "nome": "SANTANDER BR",            "yf": "SANB11.SA"},
    "SUZB3":  {"cd_cvm": 13986, "nome": "SUZANO",                 "yf": "SUZB3.SA"},
}
